# Generated by Django 3.1.5 on 2021-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeon',
            name='fechaLanzamiento',
            field=models.CharField(max_length=50, verbose_name='Fecha de lanzamiento'),
        ),
    ]
